Repository cert-manager/sample-external-issuer, pull requests merged in 2021-04, with the labels that each got.

#11 Cert manager 1.3 approval
  Makefile
  README.md
  go.mod
  go.sum
  internal/controllers/certificaterequest_controller.go
  internal/controllers/certificaterequest_controller_test.go
Labels: dco-signoff: yes, lgtm, size/L

#13 Run unit-tests using GitHub actions
  .github/workflows/test.yaml
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#12 Adds optional flag that disables checking the approved condition. This condition is checked by default.
  README.md
  internal/controllers/certificaterequest_controller.go
  internal/controllers/certificaterequest_controller_test.go
  main.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#16 If a CertificateRequest has been denied, set the FailureTime and set a Ready=False condition with Reason=Denied
  README.md
  go.mod
  go.sum
  internal/controllers/certificaterequest_controller.go
  internal/controllers/certificaterequest_controller_test.go
  main.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#17 Add an OWNERS file
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/S

#15 Release process with Docker image published to ghcr.io
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .gitignore
  Dockerfile
  Makefile
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/L
